---
title: ""
output: html_document
params:
  revue: cybergeo.revues.org
  date: yesterday
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r, results='asis'}
cat(paste0("Fréquentation de la revue ", params$revue))
```


```{r sources}

source(file = "./get_piwik_data.R")
library(httr)
library(purrr)
library(tidyverse)
library(leaflet)
library(rnaturalearth)
library(sf)
library(stringr)
library(hrbrthemes)
library(plotly)
```

```{r carte}


# capitales <- ne_download(type = "populated_places", load = TRUE, returnclass = "sf", destdir = getwd())
# save(capitales, file = "./capitales.Rdata")
load("./capitales.Rdata")

df <- getCountries(revue = params$revue, date = params$date, idSite = case_when(str_detect(params$revue, "hypotheses.org") ~ 4,
                                                                                str_detect(params$revue, "revues.org") ~ 3,
                                                                                str_detect(params$revue, "books.openedition.org") ~ 5,
                                                                                str_detect(params$revue, "calenda.org") ~ 6,
                                                                                TRUE ~ 3))

capitales %>% 
  filter(FEATURECLA %in% "Admin-0 capital") %>% 
  mutate(code = tolower(ISO_A2)) %>% 
  left_join(df, by = c("code")) %>% 
  leaflet(width = 1000, height = 800) %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addCircleMarkers(radius = ~ log(nb_visits, base = 1.5), 
                   stroke = FALSE, 
                   color = "#FF8227",
                   fillOpacity = 0.6,
                   label = ~ paste0(SOV0NAME, " : ", nb_visits, " visites"))

```

```{r, fig.height=10}
df %>% 
  select(-id, -nb_actions, -code) %>% 
  gather(visites, valeurs, nb_visits:nb_uniq_visitors) %>% 
  arrange(desc(visites), desc(valeurs)) %>% 
  group_by(visites) %>% 
  slice(1:20) %>% 
  arrange(valeurs) %>% 
  ungroup() %>% 
  mutate(pays = forcats::fct_inorder(pays)) %>% 
  ggplot(aes(x = pays, y = valeurs)) +
  geom_col(aes(fill = visites), position = "dodge") +
#  geom_text(aes(label = valeurs)) +
  scale_fill_manual(labels = c("visiteurs uniques", "visites"), name = "", values = c("#07B7D9", "#FF8227")) +
  coord_flip() +
  theme_ipsum(grid = "X") +
  theme(legend.position = "bottom") +
  labs(x = "", y  = "")
  
```

